---
- hosts: webservers
  become: yes
  tasks:
    - name: Install packages
      apt: name={{ item }} state=present
      with_items:
        - apache2
    - name: start apache2 server
      service: name=apache2 state=started
