---
- hosts: webservers
  become: yes
  vars_files:
    - ../group_vars/webservers.yml
  tasks:
    - name: Install packages
      apt: name={{ item }} state=present
      with_items:
        - apache2
    - name: start apache2 server
      service: name=apache2 state={{ apache_state }}
