---
- hosts: webservers
  become: yes
  vars_files:
    - ../group_vars/webservers.yml
    - ../hosts_vars/front1.yml
    - ../group_vars/all.yml
  tasks:
    - name: Install packages
      apt: name={{ item }} state=present
      with_items:
        - apache2
    - name: start apache2 server
      service: name=apache2 state={{ apache_state }}
    - name: copy index for remote server
      copy: src={{ source }}/index.html dest={{ destination }}
    - name: restart server 
      service: name=apache2 state={{ restart_service }}
